version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: projects
      POSTGRES_USER: projects
      POSTGRES_PASSWORD: StrongPass123
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
