name: Main
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "18.x"
      - name: Install dependencies
        run: npm install

      - name: Run Docker
        run: docker compose up -d


      - name: Wait for Postgres
        run: sleep 10

      - name: Check Postgres Container Logs
        run: docker-compose logs postgres

      - name: Migrate Prisma
        run: npm run migrate

      - name: Run test
        run: npm test
